### ISSUE TITLE
Specifications link in readme is broken

### ISSUE THREAD

**Issue by codebyalokgupta** [ehn-digital-green-development/hcert-spec#63] opened 2021-04-27 12:59 UTC
on the page https://github.com/ehn-digital-green-development/hcert-spec under specifications thee link given as below is. broken - https://github.com/ehn-digital-green-development/hcert-spec/blob/v105/hcert_spec.md

It could be for main branch - https://github.com/ehn-digital-green-development/hcert-spec/blob/main/hcert_spec.md

**Comment by jschlyter** [comment] 2021-04-27 13:00
Please check https://github.com/ehn-digital-green-development/hcert-spec/tree/next, next pending release

**Comment by marado** [comment] 2021-05-25 10:50
This seems to be a duplicate of #53 .

**Closed** 2021-05-25 11:51 UTC
